### ISSUE TITLE
px4crtl yaw bug

### ISSUE THREAD

**Issue by Poaos** [aphasiayc/px4ctrl#2]
您好，我最近在使用px4ctrl控制四旋翼时遇到了问题:
 px4ctrl控制无人机自动起飞并悬停后，遥控器控制四旋翼的油门，roll，pitch这些都正常，但是控制yaw时，如果yaw角度变化大于100度（大概），无人机就会开始圆周运动，并且是半径越转越大那种（最后会失速往一个方向炸鸡）。config文件中的参数我基本上都已经对应修改过了，那个kp kv也尝试改小过，都是一样的效果。当然，如果我在上述情况下立马切出offboard，飞机就能够一下子稳定住。
这个问题是我在飞egoplanner的时候，先设定目标点（3，0，1），正常飞过去，再设定（2，0，1），无人机转向后就会直接往某个方向炸鸡，多次排查后发现的。我目前判断问题应该是px4ctrl本身的，因为纯t265的时候，使用px4自己的位置控制没有出现过这些情况。不知道您是否遇到过这种情况，或者有大概的问题解决思路?

目前采用t265定位，px4ctrl订阅 /mavros/local_position/odom和/mavros/imu/data，只不过他们都频率都没有高于100hz。不知道是否影响。

**Comment by Poaos** [comment]
已经得到回复啦😄

![Screenshot_20230412_202559.jpg](https://user-images.githubusercontent.com/72333616/231456417-ce7fa5b6-d0d9-4be6-9b15-9143defe0330.jpg)

**Comment by aofeng1205** [comment]
> 已经得到回复啦😄
> 
> ![Screenshot_20230412_202559.jpg](https://user-images.githubusercontent.com/72333616/231456417-ce7fa5b6-d0d9-4be6-9b15-9143defe0330.jpg)

hxd 这是什么论坛吗？

**Comment by Poaos** [comment]
> > 已经得到回复啦😄
> > ![Screenshot_20230412_202559.jpg](https://user-images.githubusercontent.com/72333616/231456417-ce7fa5b6-d0d9-4be6-9b15-9143defe0330.jpg)
> 
> hxd 这是什么论坛吗？

我之前在浙大的仓库下面提的issue，还是github
https://github.com/ZJU-FAST-Lab/Fast-Drone-250/issues/53#issuecomment-1531635769
